version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  filter:
    jobs:
      - path-filtering/filter:
          base-revision: develop
          config-path: .circleci/workflows.yml
          mapping: |
            packages/foo/.* run-foo true
            packages/bar/.* run-bar true
